### PR TITLE
[G2M] Icons for lumen-table replacing all material-ui/icons 

### PR DESCRIPTION
**Pull request by kc-leung**
icons for https://github.com/EQWorks/lumen-table/pull/32

### CODE REVIEW

**Review by woozyking — COMMENTED** [review]
perhaps more of a design aspect issue (@sallkall) -- `ArrowUp` seems to be slightly bolder than `ArrowDownRegular` while they seem to be symmetrical. perhaps the implementation of one of them can be another but turning 180 degrees through styling? this way they would be theoretically highly consistent

up/down diff

up/down diff 200%
(200% zoom)

**Comment by kc-leung** [comment]
> > perhaps more of a design aspect issue (@sallkall) -- `ArrowUp` seems to be slightly bolder than `ArrowDownRegular` while they seem to be symmetrical. perhaps the implementation of one of them can be another but turning 180 degrees through styling? this way they would be theoretically highly consistent
> > up/down diff
> > up/down diff 200% (200% zoom)
> 
> > perhaps more of a design aspect issue (@sallkall) -- `ArrowUp` seems to be slightly bolder than `ArrowDownRegular` while they seem to be symmetrical. perhaps the implementation of one of them can be another but turning 180 degrees through styling? this way they would be theoretically highly consistent
> > up/down diff
> > up/down diff 200% (200% zoom)
> 
> @woozyking yeah the icon naming is a bit out of control...
> 
> @kc-leung in this case maybe also update the `ArrowUp` icon name to `ArrowUpRegular` to match your new `ArrowDownRegular`

we will still need to keep it as ArrowUp if we want backward compatibility otherwise the projects that uses ArrowUp will need to update it but I think it is necessary the change

**Review by woozyking — APPROVED** [review]
@sallkall what about the weight/bold discrepancy (or is it just me)

**Review by hyx131 — APPROVED** [review]
> we will still need to keep it as ArrowUp if we want backward compatibility otherwise the projects that uses ArrowUp will need to update it but I think it is necessary the change

not great for maintenance but we perhaps can temporarily export both `ArrowUp` and `ArrowUpRegular` pointing to the same icon... 😬

**Comment by woozyking** [comment]
> not great for maintenance but we perhaps can temporarily export both ArrowUp and ArrowUpRegular pointing to the same icon... 😬

yea aliasing it would do for the short-term

**Pull request merged**
