### PR TITLE
[G2M] textfield - fix focus, onSubmit & suffix problems

### LINKED ISSUE #102: TextField - fixes for unexpected behaviours
**Problems:**

1. The styling stays on focus after selecting a value and clicking elsewhere on the page
2. Adding a suffix renders the TextField unusable for numeric values:

https://user-images.githubusercontent.com/41120953/153695430-d13a7e8e-6579-4d7b-aa3d-2c1de7640f73.mov

3. After entering a value in the TextField, if we press Enter, the whole page crashes:

https://user-images.githubusercontent.com/41120953/153651358-c3463544-bc03-4b5f-b978-504601a65085.mov

### PR DESCRIPTION
**Pull request by kc-leung**
fixes #102

### CODE REVIEW

**Comment by geoerika** [comment]
@kc-leung I am trying to test this directly in widget-studio but the local build for lumen-labs I am using crashes my storybook entirely. If it's possible, can you change the package and make a pre-release on this branch for me to try out please?

**Comment by kc-leung** [comment]
> @kc-leung I am trying to test this directly in widget-studio but the local build for lumen-labs I am using crashes my storybook entirely. If it's possible, can you change the package and make a pre-release on this branch for me to try out please?

last pre-release was in version   "version": "0.1.0-alpha.27" and it is already in   "version": "0.1.0-alpha.28"  so there is not need to change the package version

**Review by geoerika — CHANGES_REQUESTED** [review]
The code looks fine, the active border now changes when out of focus and pressing the Enter doesn't crash the page, but, after I used the pre-release from this branch, I get this funny styling in the textField when I use it with type='number'. Perhaps you should add temporarily a storybook with such a TextField type to test in lumen-labs as well. I removed all classes for styling and a second border appears inside the TextField (see below).
This is the settings I am using in widget-studio:
```
 <TextField
                    type='number'
                    deleteButton={false}
                    placeholder={'Value'}
                    value={uniqueOptions.lineWidth?.value?.toString() ??
                      typeInfo[type].uniqueOptions.lineWidth.toString()}
                    min={1}
                    max={100}
                    step={1}
                    onChange={v => userUpdate({ uniqueOptions: { lineWidth: { value: Number(v) } } })}
                    // onSubmit={(e) => e.nativeEvent.preventDefault()}
                    // classes={{ container: classes.textFieldContainer, input: textFieldlInput }}
                  />
 ```
                  
Screen Shot 2022-02-14 at 4 10 34 PM

**Review by geoerika — COMMENTED** [review]
@kc-leung cannot give approval because my local testing in widget-studio fails. Perhaps @vxsl can do that instead.

**Comment by vxsl** [comment]
> @kc-leung cannot give approval because my local testing in widget-studio fails. Perhaps @vxsl can do that instead.

approved :+1:

https://user-images.githubusercontent.com/53827672/154139371-27ff6c01-72cf-4021-a94a-e7854696b716.mp4

(you can't see it but I am pressing the enter button in this video lol)

**Review by vxsl — APPROVED** [review]

**Comment by geoerika** [comment]
> > @kc-leung cannot give approval because my local testing in widget-studio fails. Perhaps @vxsl can do that instead.
> 
> approved 👍
> 
>  2022-02-15.14-58-37.mp4 
> (you can't see it but I am pressing the enter button in this video lol)

@vxsl Is it still staying active (the border stays blue after you input a number and you move on to another button)? That was one of the features this PR should have solved...

**Comment by vxsl** [comment]
> @vxsl Is it still staying active (the border stays blue after you input a number and you move on to another button)? That was one of the features this PR should have solved... that's what I am still seeing it happens in widget-studio.

@geoerika oh, no, that seems to still be the case: 
image

**Comment by geoerika** [comment]
> > > @kc-leung cannot give approval because my local testing in widget-studio fails. Perhaps @vxsl can do that instead.
> > 
> > 
> > approved 👍
> > 2022-02-15.14-58-37.mp4
> > (you can't see it but I am pressing the enter button in this video lol)
> 
> @vxsl Is it still staying active (the border stays blue after you input a number and you move on to another button)? That was one of the features this PR should have solved... that's what I am still seeing it happens in widget-studio.

The crash on pressing button was already in widget-studio as I added an onSubmit to handle it in TextField in MapLayerDisplay.... so, try removing those. I will try again to test this locally after dinner. Wait merging this @kc-leung until I say something.

**Review by geoerika — APPROVED** [review]
I managed to test this locally in widget-studio last night and everything works fine now! Thanks a lot @kc-leung ! Would you mind changing package version and also create a pre-release on this branch to include these changes in tomorrow's widget-studio release?

**Pull request merged**
