### PR TITLE
[G2M] Accordion/auto height

### PR DESCRIPTION
**Pull request by vxsl**
Addresses #58 in which `details` height does not transition when its desired height is not explicitly stated.

I ended up making this behaviour optional with the `autoHeight` prop in `Accordion.Panel`, as it was breaking normal behaviour in the storybook. I'm pretty sure this behaviour is preferable in most cases, but figured we should preserve the existing functionality for backwards compatibility.

before:

https://user-images.githubusercontent.com/53827672/139756313-610a0641-2e0c-4c3f-946a-415d8842438d.mp4

after:

https://user-images.githubusercontent.com/53827672/139756013-580982f3-1ce9-429f-b10d-f584317f8c4b.mp4

### CODE REVIEW

**Review by sallkall — COMMENTED** [review]
This is great! 
One issue, I'm not sure if it's something that came up as a result of your recent changes but the `minus` icon in the left-bordered accordions is now displayed side-ways: 
image

It should toggle between a minus and a plus sign 🤔

**Comment by vxsl** [comment]
@sallkall oh good catch, let me take a look at it and I'll push the fix here.

**Review by sallkall — APPROVED** [review]

**Review by kc-leung — APPROVED** [review]
the h-10 class is replaced when a custom class is passed down if i am not wrong. Would this change allows the user to modify it's height from the custom class using css?

**Comment by vxsl** [comment]
> the h-10 class is replaced when a custom class is passed down if i am not wrong. Would this change allows the user to modify it's height from the custom class using css?

@kc-leung this change introduces the `autoHeight` prop, which if `true` makes `details` have height of its content. To be honest I didn't test mixing `autoHeight={true}` and explicit height from `classes={{details:[...]}}`. But if you leave `autoHeight={false}` (it is false by default) then the existing behaviour should be unchanged.

**Pull request merged**
