### PR TITLE
[G2M] Skeleton layouts

### PR DESCRIPTION
**Pull request by Hamaad102**
Adds alternative skeleton layouts

- Added layouts that represent a bar + pie graph, map and stats

### Bar
Screenshot 2022-12-12 at 8 40 29 AM

### Map
Screenshot 2022-12-12 at 8 40 48 AM

### Pie
Screenshot 2022-12-12 at 8 40 58 AM

### Stat
Screenshot 2022-12-12 at 8 41 09 AM

### CODE REVIEW

**Review by vlatawiec — APPROVED** [review]
Looks great from a UI side! 

When implementing, we'll just have to be mindful of svg/image size (these example images look very large for the overall "widget" size.), since we do want these "Skeleton Blocks" to be mostly white space, and the image may scale based on widget size (which is not ideal) but dw about that atm. Thanks for your hard work!

**Comment by Hamaad102** [comment]
> Looks great from a UI side!
> 
> When implementing, we'll just have to be mindful of svg/image size (these example images look very large for the overall "widget" size.), since we do want these "Skeleton Blocks" to be mostly white space, and the image may scale based on widget size (which is not ideal) but dw about that atm. Thanks for your hard work!

Yes, definitely agree. There is logic implemented for the svg that allows it to scale between two fixed widths depending on whether the container is over 900px's in width. The examples use a container of 500px which definitely appear large; if you think there will be potential applications of this component that will get this small I can add another breakpoint?

**Comment by vlatawiec** [comment]
> 

Good idea, we are looking at reducing the size of some widgets based on user feedback (for v2.6 tentatively) so I will take a look at the smallest widget versions (only really applicable to stat/pie widgets) and will get back asap with any other needed breakpoints.

**Review by kc-leung — APPROVED** [review]
looks nice! Are you adding the custom case for the user in future iteration?

**Comment by Hamaad102** [comment]
> looks nice! Are you adding the custom case for the user in future iteration?

Yes, I'll create an issue for that and add that around the same time we have a clear idea about the size of the widgets

**Pull request merged**
