### PR TITLE
[G2M] Message

### PR DESCRIPTION
**Pull request by hyx131**
**Changes:**
- add `Message` component
- fix `TextField` no-value error
- add `Question` icon

**Screenshots:**
Screen Shot 2022-04-19 at 2 06 20 PM

### CODE REVIEW

**Review by sallkall — COMMENTED** [review]
Looks good.
One edge case - at high zoom levels the description/title is overflowing the container. Maybe we should also use the overflow-x/y scroll here @hyx131 
image

**Comment by hyx131** [comment]
> Looks good. One edge case - at high zoom levels the description/title is overflowing the container. Maybe we should also use the overflow-x/y scroll here @hyx131 image

sounds good, are we doing horizontal scroll or vertical scroll?

**Comment by sallkall** [comment]
> > Looks good. One edge case - at high zoom levels the description/title is overflowing the container. Maybe we should also use the overflow-x/y scroll here @hyx131
> 
> sounds good, are we doing horizontal scroll or vertical scroll?

Hmm I think ideally we should offer both, since you don't know if it'll be used in a fixed-width or fixed-height UI

**Comment by hyx131** [comment]
> > > Looks good. One edge case - at high zoom levels the description/title is overflowing the container. Maybe we should also use the overflow-x/y scroll here @hyx131
> > 
> > 
> > sounds good, are we doing horizontal scroll or vertical scroll?
> 
> Hmm I think ideally we should offer both, since you don't know if it'll be used in a fixed-width or fixed-height UI. **or** for the hasTitle one, use vertical, the description only one we do horizontal scroll

added for both lol

**Review by sallkall — APPROVED** [review]

**Pull request merged**
