### PR TITLE
[G2M] login module design updated

### LINKED ISSUE #163: Login  Design
Update Login module to be inline with new [design](https://www.figma.com/file/RB5JLQk54JgzUK6a50ej7S/COX-Dashboard?node-id=4814%3A142402&t=WYz6K7U4JfMJhPw9-0)

### PR DESCRIPTION
**Pull request by Hamaad102**
resolves #163 

### Changes
- Added props to sider image so user can modify style
- Updated frontend design to reflect changes found on [figma](https://www.figma.com/file/RB5JLQk54JgzUK6a50ej7S/COX-Dashboard?node-id=4814%3A142402&t=WYz6K7U4JfMJhPw9-0)

#### Before
Screenshot 2023-01-17 at 3 34 23 PM
Screenshot 2023-01-17 at 3 34 06 PM

#### After
Screenshot 2023-01-17 at 4 31 28 PM
Screenshot 2023-01-17 at 4 30 45 PM

### CODE REVIEW

**Review by kc-leung — APPROVED** [review]
remember to add for what project this is for

**Review by kc-leung — APPROVED** [review]

**Review by vlatawiec — COMMENTED** [review]
Looks good! Thank you for your hard work. I have a few picky requests from the UI side. First (this is completely my fault) the text on the left-most image section needs to be updated to reflect new design system text (shown in design now, sorry!). Second, is it possible to increase the padding between the "Division line" and the bottom logo on the right-most UI sections? It is slightly smaller than intended (lmk if there's a reason, if so thats fine!). Finally, you can get rid of the lower "lorum ipsum" text on the right-most UI sections (that was added with V1 to accommodate a "copyright message, technical disclaimer, etc.) and was removed in 2.4! Let me know if you have any questions or concerns @Hamaad102, thank you again!

**Comment by vlatawiec** [comment]
Also if the line breaking on the "Login" page description could be changed to accomodate 2 lines of text in stead of the current 3, that would be great, if not (or if it requires any substantial effort) then no worries!

**Comment by Hamaad102** [comment]
@vlatawiec I can get all these changes in, no worries

For the the last point the reason the content is split in three lines is because of the 'Power Report Dashboard' text. In actual deployment it would either say Dealertrack (or presumably Paymi?) which would both fit within 2 lines.

**Review by vlatawiec — APPROVED** [review]
Makes perfect sense, never mind on the breaking then! Looks great, thank you!

**Review by geoerika — APPROVED** [review]

**Pull request merged**
