### PR TITLE
[G2M] Radio button

### LINKED ISSUE #160: Radio Button
Add radio buttons that follow the spec laid out on [figma](https://www.figma.com/file/vbTlH7kDiG4g65TjsJoDIa/lumen-labs?node-id=417%3A930&t=SS6VXao6od6hPoVX-0)

Screenshot 2023-01-09 at 12 55 30 PM

### PR DESCRIPTION
**Pull request by Hamaad102**
resolves #160 

### Changes
- Added Radio + RadioGroup component

#### Horizontal
Screenshot 2023-01-11 at 12 14 41 PM

#### Horizontal + Left Label
Screenshot 2023-01-11 at 1 32 28 PM

#### Vertical
Screenshot 2023-01-11 at 12 14 31 PM

### Vertical + Left Label
Screenshot 2023-01-11 at 1 32 17 PM

### CODE REVIEW

**Review by kc-leung — CHANGES_REQUESTED** [review]
- lets center the label to the radio button so they are in line vertically. Also, can you add an option and sample for the label to be on the left side of the radio button?
- remember to add forwardRef for the main/root container

**Comment by geoerika** [comment]
> * lets center the label to the radio button so they are in line vertically. Also, can you add an option and sample for the label to be on the left side of the radio button?
> * remember to add forwardRef for the main/root container

Agree with KC's comments!

**Review by geoerika — CHANGES_REQUESTED** [review]
Waiting for implementation of KC's sugestions.

**Review by vlatawiec — APPROVED** [review]
Agree with KC/Erika's comments, otherwise looks good! :)

**Review by kc-leung — CHANGES_REQUESTED** [review]
take a look on older component passing down {...rest} to the main container of the component for any other extra props for the div. Also, add forwardRef for radio component as well not only radioGroup

**Comment by Hamaad102** [comment]
> take a look on older component passing down {...rest} to the main container of the component for any other extra props for the div. Also, add forwardRef for radio component as well not only radioGroup

In this instance would the unique value for each radio button not serve the same purpose?

**Comment by kc-leung** [comment]
> > take a look on older component passing down {...rest} to the main container of the component for any other extra props for the div. Also, add forwardRef for radio component as well not only radioGroup
> 
> In this instance would the unique value for each radio button not serve the same purpose?

it is for the case if user only wants to use the radio component without radioGroup. For {...rest} is if user wants to add id,name,etc any other container html props

**Review by geoerika — APPROVED** [review]

**Review by kc-leung — APPROVED** [review]

**Pull request merged**
