### PR TITLE
[G2M] Refactor loader component custom class usage

### PR DESCRIPTION
**Pull request by kc-leung**
- Refactor custom class usage for Loader component

### CODE REVIEW

**Review by vlatawiec — APPROVED** [review]
UI wise looks good, will need the "Simple Loader" version to follow backdrop loader design if possible (Font, spacing and throbber placement).

**Review by Hamaad102 — APPROVED** [review]
Looks good

**Comment by kc-leung** [comment]
> UI wise looks good, will need the "Simple Loader" version to follow backdrop loader design if possible (Font, spacing and throbber placement). 

Yes, user can customize all the styling the simple one is for sample purpose on how it looks if nothing is modified or added

**Review by geoerika — COMMENTED** [review]
@kc-leung Sorry, just saw this. Perhaps we should add some space between the title & the loader icon. In the next PR.

**Pull request merged**
