### PR TITLE
[G2M] Dropdown - add dropdownSelect & dropdownSelectSteps Components 

### LINKED ISSUE #29: Components Library: New Select Component
# 🎯 Usage 
- Allows user input by selecting from a list of predefined options
- Best used in situations where there are more than 3 options to select from.

# 🎭  Behaviours
- **Display Options**: For any single option, the user can also choose to display an icon and/or a description.
- **Width**: The width of an option element will on default fill the dropdown container. 
- **Sizes**: Two predefined sizes are provided: large and medium.
- **Selection Types**: We offer simple selections (i.e. select process takes only 1 click), and more complex selections such as tree-select, step-select, and linked select (i.e. requires multiple clicks to complete selection and may include multiple dropdown and input fields).
- **Smart Select**: Supports autocomplete and search features.

# 🧩 Style Variations 
- `Simple Select` → A simple select with text options only
- `Grouped Select` → Options in the dropdown are divided by categories/labels
- `Select With Divider` → Options in the dropdown are divided by a divider
- `Select With Icons` → Simple select where each option is displayed with an icon
- `Select With Description` → Simple select where each option is displayed with a description
- `Multi-select` → Select multiple options from the dropdown
- `Tree-select` → A cascade dropdown where options are grouped in a tree-structure
- `Step-select` → Options are grouped and displayed across multiple dropdown steps
- `Linked-select` → Selection that relies on a previous selection to be completed before it becomes available

# 💟 Icons Used
- [check](https://app.streamlinehq.com/icons/streamline-light/interface-essential/form-validation/check-1)
- [arrow-left](https://app.streamlinehq.com/icons/streamline-light/arrows-diagrams/arrows/arrow-left-1)
- [arrow-right](https://app.streamlinehq.com/icons/streamline-light/arrows-diagrams/arrows/arrow-right-1)

# 🔗 Zeplin Link
- [Select](https://zpl.io/ag16Jq0)

# 🔢  Attributes

Property | Type | Default Value | Description
--- | --- | --- | ---
`size` | `large` \| `medium` | `medium` | The size of Select
`defaultValue` | `ReactNode` | `-` | The initial selected option
`placeholder` | `ReactNode` | `-` | The placeholder option shown in the input box
`disabled` | `boolean` | `'false'` | Sets Select to disabled state
`options` | `{ label, value }[]` | `-` | List of selectable options
`dropdownType` | `string` | `-` | Customize the type of dropdown used
`input` | `ReactNode` | `-` | The selected option

# 🔍 Design Preview
Select

### PR DESCRIPTION
**Pull request by kc-leung**
fix #29 
- Added dropdownSelect component with group, divider, icons, description & multiselect variants
- Added dropdownSelectSteps component for steps vartiant
- Added Linked variant in storybook using dropdownSelect component
- Added dropdown-data.js for sample data used in Dropdown storybook
- Added disabled option for dialogBase component
- Added out of component click close even if open is controlled
- Added arrow-left & validation-check Icons
- Added additional spacing option `'3px': '0.188rem', '7px': '0.438rem' & '9px': '0.563rem'` to tailwindConfig
- Added fontSize option `'11px': ['0.688rem', { lineHeight: 1.45 }]` to tailwindConfig

TO DO: 
- Update lumen-tree styling for Tree variant

**Created a new PR because the old one wasn't updating to the latest push**

### CODE REVIEW

**Review by sallkall — CHANGES_REQUESTED** [review]
Thanks for making the updates 💯 

One small issue, the **medium** linked select is behaving weirdly. The second 'linked' select dropdown gets triggered right after user makes selection in the first one, it _should_ wait for the user to open instead. The large one is correct, can you fix the medium so it is the same as the large linked select? 

Issue with medium linked-select:

https://user-images.githubusercontent.com/33563070/129041991-a933ee8c-a314-4928-be08-e11b666d457a.mov

-------
Correct behaviour with large linked-select:

https://user-images.githubusercontent.com/33563070/129042198-a2855a59-e6d1-4369-ac82-5913b2fef39f.mov

**Comment by kc-leung** [comment]
> Thanks for making the updates 💯
> 
> One small issue, the **medium** linked select is behaving weirdly. The second 'linked' select dropdown gets triggered right after user makes selection in the first one, it _should_ wait for the user to open instead. The large one is correct, can you fix the medium so it is the same as the large linked select?
> 
> Issue with medium linked-select:
> Screen.Recording.2021-08-11.at.9.50.39.AM.mov
> 
> Correct behaviour with large linked-select:
> Screen.Recording.2021-08-11.at.9.51.17.AM.mov

it is fixed now please have a look again 👍

**Review by woozyking — APPROVED** [review]

**Comment by sallkall** [comment]
> > Thanks for making the updates 💯
> > One small issue, the **medium** linked select is behaving weirdly. The second 'linked' select dropdown gets triggered right after user makes selection in the first one, it _should_ wait for the user to open instead. The large one is correct, can you fix the medium so it is the same as the large linked select?
> > Issue with medium linked-select:
> > Screen.Recording.2021-08-11.at.9.50.39.AM.mov
> > Correct behaviour with large linked-select:
> > Screen.Recording.2021-08-11.at.9.51.17.AM.mov
> 
> it is fixed now please have a look again 👍

Looks good
Question - will the dropdown close automatically when someone finish selecting an option? I feel like it should close automatically for all cases except for multi-select drop-downs which will only close by manually clicking outside of that dropdown area.

**Comment by kc-leung** [comment]
> > > Thanks for making the updates 💯
> > > One small issue, the **medium** linked select is behaving weirdly. The second 'linked' select dropdown gets triggered right after user makes selection in the first one, it _should_ wait for the user to open instead. The large one is correct, can you fix the medium so it is the same as the large linked select?
> > > Issue with medium linked-select:
> > > Screen.Recording.2021-08-11.at.9.50.39.AM.mov
> > > Correct behaviour with large linked-select:
> > > Screen.Recording.2021-08-11.at.9.51.17.AM.mov
> > 
> > 
> > it is fixed now please have a look again 👍
> 
> Looks good
> Question - will the dropdown close automatically when someone finish selecting an option? It should close automatically for all cases except for multi-select drop-downs which will only close by manually clicking outside of that dropdown area.

no, it doesn't automatically close I will add it then except for multiselect.

**Review by sallkall — APPROVED** [review]

**Comment by hyx131** [comment]
do we have the option to customize the trigger component for opening the select menu?
e.g. dropdowns opened by buttons instead of input for example:
Screen Shot 2021-08-12 at 10 38 41 AM

**Comment by kc-leung** [comment]
> do we have the option to customize the trigger component for opening the select menu?
> e.g. dropdowns opened by buttons instead of input/select for example:
> Screen Shot 2021-08-12 at 10 38 41 AM

no we don't I will add it now

**Comment by kc-leung** [comment]
> _minor note:_
> For this variant wonder if its possible to implement using html `select` + `option` tags (at least for some parts of it), would prefer using html tags whenever we can, but if its difficult to support all our component features, we can dismiss this note

for state management? lets open up a thread for that on SLACK

**Review by hyx131 — APPROVED** [review]

**Pull request merged**
